### ISSUE TITLE
Feedback | Dashboard Stakeholders & Features

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/wp2.2_docs#1]
(you can check boxes below for each point that has been processed ← doesn't need to be integrated; 'dismissed' is a valid result of processing :)  )

# Stakeholders

- [x] merge `manufacturer` & `read-only replicator` since it seems to result in very similar information needs in practice
- [x] expand the group `market researcher` to `researcher` (+ journalists etc.) → don't know why we should focus on market research only
- [x] add a mention how `project owners` and `direct contributors` would use the dashboard (e.g. for the purpose of PM, PR or quality checks) (e.g in `Description`; B19 in the first sheet)

Information needs:

- [x] delete `Skills` and move features to remaining categories (e.g. `community organisation` and `contributor profiles`)

 # Features

- add LICENSE information
  - [x] "this project uses a…"
    - "free/open license that was specifically designed for hardware → pretty neat!"
    - "free/open license that was _not_ specifically designed for hardware, but still works"
    - "license that was not endorsed neither by the FSF nor the OSI (according to the [SPDX list](https://spdx.org/licenses/)); it might still work, but better have a look onto it"
  - [x] easy: what kind of license is that (strong copyleft/weak copyleft/permissive)
  - [x] complete: what obligations come with that specific license when dealing with the technical documentation? (e.g. attribution when redistributing; ShareAlike etc.)
- [x] add OTRL/ODRL badge (based on self-assessment) (see first draft [here](https://github.com/OPEN-NEXT/OKH-LOSH/blob/master/OTRL.md); TTL [here](https://github.com/OPEN-NEXT/OKH-LOSH/blob/master/OTRL.ttl))
- [x] add `DIN SPEC 3105-1 compliant` (also based on self-assessment)

**Comment by penyuan** [comment]
Processed all items. Thanks! Closing issue.
